### ISSUE TITLE
Upgrade to recent django?

### ISSUE THREAD

**Issue by jdunck** [freelawproject/recap-server#1]
I saw from the settings code that this is running on an old django version.  (I can't tell which, but the use of DATABASE_* rather than DATABASES = {} was the tell.)

I'm familiar with django.  How can I help?

**Comment by brianwc** [comment]
This is (finally) being addressed by #48 (upgrade dependencies) and #65 (tests). @jdunck if you are still interested (two years later!) then lots of this sort of work is ongoing currently. Closing this to track separately in issues listed.
