### ISSUE TITLE
Appellate Parser Should Capture Useful Metadata

### ISSUE THREAD

**Issue by thinkcomp** [freelawproject/recap-server#14]
At the top of the "General Docket" page for a case (also known as TransportRoom?servlet=CaseSummary.jsp) I see things like:

Court of Appeals Docket #: 12-73415 	Docketed: 10/23/2012
Harwinder Sing-Grewal v. Eric Holder, Jr.
Appeal From: Board of Immigration Appeals
Fee Status: IFP
Case Type Information:
     1) agency
     2) review
     3) San Francisco Northern Ca
Originating Court Information:
     District: BIA-1 : A089-474-561
     Date Filed: 10/23/2012
     Date Rec'd COA:
     10/23/2012

Can we capture all of this? Lots more useful information here.

**Comment by brianwc** [comment]
Appears that a commit 2 years ago addressed this.
