### ISSUE TITLE
Appellate docket parser ignores non-documents

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap-server#22]
The docket report should include all docket items, not just PDF documents.
Did a query for all docket events from 1/1/2013 on
http://ia601701.us.archive.org/17/items/gov.uscourts.ca2.12-3200/gov.uscourts.ca2.12-3200.docket.html

and got back the HTML here:
http://pastebin.com/RiEMD8aP

Which included:
03/11/2013	 148  	CASE CALENDARING, for the week of 05/06/2013, PROPOSED.[871308] [12-3200] 

e.g.
![Screen shot 2013-04-03 at 12 24 38 AM](https://f.cloud.github.com/assets/1270718/332132/74ff8f9c-9c16-11e2-89d1-8222f1459bb6.png)

but the docket.html from archive.org skips from 146 to 150.

**Comment by mlissner** [comment]
I'm closing this one down so the discussion can happen in a single place. The newer issue on this topic has a bit more discussion, I think.
