### ISSUE TITLE
Parties incorrectly parsed in Swartz, others. 

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap-server#26]
There's some irony in reporting bugs in RECAP's handling of United States v. Swartz.

The parties section of http://ia700504.us.archive.org/29/items/gov.uscourts.mad.137971/gov.uscourts.mad.137971.docket.html misses several of the parties. It shows the 6 attorneys representing the defendant (Swartz). But it does not show the 3 attorneys representing the Plaintiff (USA), nor the 2+1 attorneys representing 2 intervenors.

I think this is a longstanding breakage; sorry for not reporting it earlier.

Here's the HTML saved by Firefox from PACER: https://gist.github.com/5378539

**Comment by brianwc** [comment]
Appears that this was fixed in a commit 2 years ago.
