### ISSUE TITLE
CAND's  3:13-cv-00815-SC doesn't seem to function in RECAP?

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap-server#27]
Carl Malmud's case,  3:13-cv-00815-SC Public.Resource.org v. Sheet Metal and Air Conditioning Contractors' National Association, Inc. in ecf.cand.uscourts.gov, doesn't seem to work with RECAP.

Neither the docket nor the files seem to be successfully uploaded.
See https://gist.github.com/johnhawkinson/5548532 for logs.

**Comment by brianwc** [comment]
Whatever was wrong appears fixed. This case is fully-RECAP'd here:
https://ia601607.us.archive.org/14/items/gov.uscourts.cand.263568/gov.uscourts.cand.263568.docket.html
