### ISSUE TITLE
In query responses, "timestamp" key is misnamed and in a bad format

### ISSUE THREAD

**Issue by zestyping** [freelawproject/recap-server#4]
Responses to /recap/query include the "timestamp" field.  However, this field does not contain a timestamp at all; it contains a date.

Also, the date is in mm/dd/yy format, which is a poor design choice.  Two-digit years should have died over a decade ago.  Dates transmitted over the wire should be in Unix timestamp (seconds since epoch) or in RFC 3339 format.

**Comment by brianwc** [comment]
Closing.
