### ISSUE TITLE
Things are all kind of broken?

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap-server#44]
I feel like RECAP has been busted for me for a while.
I haven't had a chance to sit down and debug it.
Firefox 28.

But, say, retrieving recent entries in http://ia600503.us.archive.org/2/items/gov.uscourts.nyed.308557/gov.uscourts.nyed.308557.docket.html gives my nyed-NNNNNNN.pdf -type filenames, and the docket doesn't get uploaded, etc., etc.

Hrmm, I see someone manged to upload a file on 4/2, so maybe it's mostly just me. I dunno.

**Comment by mlissner** [comment]
Closing. Looks like this has been resolved for some time.
