### ISSUE TITLE
recap-server needs API to enable third party programmatic document contributions

### ISSUE THREAD

**Issue by brianwc** [freelawproject/recap-server#50]
There are others programmatically retrieving PACER documents for their own purposes. recap-server should provide an API so that those efforts could contribute their collection efforts to the RECAP archive, outside of the browser extensions. We don't want random people posting garbage into the archive, so this might be a situation where a private API key is required for posting privileges.

**Comment by mlissner** [comment]
It looks like this will be a private API, but I'll soon be posting documentation for it here: https://www.recapthelaw.org/api-latest/. 

We'll need more work on this API, but I'm going to mark this as complete. If we have specific enhancements or changes we wish to make, we should do that in fresh tickets.
